import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { DateRangeSelector } from './DateRangeSelector'
import { FreshnessAnalyzer } from './FreshnessAnalyzer'
import { StrategySelector } from './StrategySelector'
import { supabase } from '../lib/supabase'
import type { MealPlan, Recipe } from '@shared/types'
import type { FreshnessWarning } from '@shared/shoppingListTypes'

interface PreviewIngredient {
  ingredient_name: string
  quantity: number
  unit: string
  category: string
  freshness_days: number
  used_on_dates: string[]
  recipe_count: number
}

interface ShoppingListCreatorWizardProps {
  isOpen: boolean
  onClose: () => void
  mealPlans: MealPlan[]
  recipes: Recipe[]
  userId: string
  onComplete: (lists: any[]) => void
}

type Step = 'date_range' | 'analysis' | 'strategy' | 'generating'

export function ShoppingListCreatorWizard({
  isOpen,
  onClose,
  mealPlans,
  recipes,
  userId,
  onComplete
}: ShoppingListCreatorWizardProps) {
  
  const [step, setStep] = useState<Step>('date_range')
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')
  const [warnings, setWarnings] = useState<FreshnessWarning[]>([])
  const [totalIngredients, setTotalIngredients] = useState(0)
  const [perishableCount, setPerishableCount] = useState(0)
  const [safeCount, setSafeCount] = useState(0)
  
  const handleDateSelect = async (fromOrRange: string | { start: string; end: string }, to?: string) => {
    let from: string
    let toDate: string

    // Support both old format (from, to) and new format ({ start, end })
    if (typeof fromOrRange === 'object') {
      from = fromOrRange.start
      toDate = fromOrRange.end
    } else {
      from = fromOrRange
      toDate = to || fromOrRange
    }

    setDateFrom(from)
    setDateTo(toDate)

    // Use backend preview function for ingredient analysis
    try {
      const { data: previewData, error } = await supabase
        .rpc('preview_shopping_list', {
          target_user_id: userId,
          date_from: from,
          date_to: toDate
        })

      if (error) {
        console.error('Error previewing shopping list:', error)
        // Fall back to showing no ingredients
        setTotalIngredients(0)
        setWarnings([])
        setSafeCount(0)
        setPerishableCount(0)
      } else {
        const ingredients = previewData as PreviewIngredient[]
        console.log('Preview ingredients from backend:', ingredients)

        // Analyze freshness based on category shelf life
        const analysisWarnings: FreshnessWarning[] = []
        const highSeverityCategories = ['MEAT_FRESH', 'MEAT_GROUND', 'MEAT_POULTRY', 'FISH_FRESH', 'SHELLFISH']
        const mediumSeverityCategories = ['DAIRY_MILK', 'FRESH_HERBS', 'SALAD_LEAFY']

        // Group perishable items by category for warnings
        const perishableItems = ingredients.filter(ing =>
          highSeverityCategories.includes(ing.category) ||
          mediumSeverityCategories.includes(ing.category) ||
          ing.freshness_days <= 5
        )

        if (perishableItems.length > 0) {
          // Group by category for better warnings
          const byCategory = perishableItems.reduce((acc, item) => {
            if (!acc[item.category]) acc[item.category] = []
            acc[item.category].push(item)
            return acc
          }, {} as Record<string, PreviewIngredient[]>)

          for (const [category, items] of Object.entries(byCategory)) {
            const isHighSeverity = highSeverityCategories.includes(category)
            const shelfLife = Math.min(...items.map(i => i.freshness_days))
            const severity = isHighSeverity ? 'high' : shelfLife <= 3 ? 'high' : 'medium'
            const recommendation = shelfLife <= 2
              ? 'Frys in direkt eller använd inom 1-2 dagar'
              : 'Köp närmare användningsdatum för bästa fräschör'

            analysisWarnings.push({
              severity,
              category: category as any, // Type assertion for IngredientCategory
              item_count: items.length,
              message: `Håller max ${shelfLife} dagar i kyl`,
              recommendation,
              affected_items: items.map(i => i.ingredient_name)
            })
          }
        }

        setTotalIngredients(ingredients.length)
        setWarnings(analysisWarnings)

        const perishableCount = perishableItems.length
        setSafeCount(ingredients.length - perishableCount)
        setPerishableCount(perishableCount)
      }
    } catch (err) {
      console.error('Error in handleDateSelect:', err)
    }

    setStep('analysis')
  }
  
  const handleStrategySelect = async (strategy: 'include_all' | 'exclude_perishables' | 'split_lists' | 'custom') => {
    setStep('generating')

    try {
      // Generate list metadata - actual items will be generated by backend
      const listName = `Inköpslista ${new Date(dateFrom).toLocaleDateString('sv-SE', { day: 'numeric', month: 'short' })} - ${new Date(dateTo).toLocaleDateString('sv-SE', { day: 'numeric', month: 'short' })}`

      const lists = [{
        user_id: userId,
        name: listName,
        date_range_start: dateFrom,
        date_range_end: dateTo,
        status: 'active',
        split_mode: strategy === 'split_lists' ? 'split' : 'single',
        warnings: warnings
      }]

      onComplete(lists)
      handleClose()
    } catch (error) {
      console.error('Failed to generate shopping lists:', error)
      alert('Kunde inte skapa inköpslista. Försök igen!')
      setStep('strategy')
    }
  }
  
  const handleClose = () => {
    setStep('date_range')
    setDateFrom('')
    setDateTo('')
    setWarnings([])
    setTotalIngredients(0)
    onClose()
  }
  
  const handleBack = () => {
    if (step === 'analysis') {
      setStep('date_range')
    } else if (step === 'strategy') {
      setStep('analysis')
    }
  }
  
  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={handleClose}
            className="fixed inset-0 bg-black/50 z-40"
          />

          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 overflow-y-auto">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="w-full max-w-4xl bg-surface rounded-2xl shadow-2xl flex flex-col max-h-[90vh] my-8"
            >
              {/* Header */}
              <div className="p-6 border-b border-gray-200 flex-shrink-0">
                <div className="flex items-start justify-between">
                  <div>
                    <h2 className="text-2xl font-bold mb-1 flex items-center gap-2">
                      🛒 Skapa Inköpslista
                    </h2>
                    <p className="text-text-secondary">
                      {step === 'date_range' && 'Välj period att handla för'}
                      {step === 'analysis' && 'Analys av ingredienser'}
                      {step === 'strategy' && 'Välj strategi'}
                      {step === 'generating' && 'Skapar din inköpslista...'}
                    </p>
                  </div>
                  <button
                    onClick={handleClose}
                    className="text-2xl text-text-secondary hover:text-text transition-colors"
                  >
                    ✕
                  </button>
                </div>
                
                {/* Progress indicator */}
                <div className="flex items-center gap-2 mt-4">
                  {['date_range', 'analysis', 'strategy', 'generating'].map((s, index) => (
                    <div key={s} className="flex items-center">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${
                        step === s
                          ? 'bg-primary text-white'
                          : index < ['date_range', 'analysis', 'strategy', 'generating'].indexOf(step)
                          ? 'bg-green-500 text-white'
                          : 'bg-gray-200 text-gray-400'
                      }`}>
                        {index + 1}
                      </div>
                      {index < 3 && (
                        <div className={`w-12 h-1 ${
                          index < ['date_range', 'analysis', 'strategy', 'generating'].indexOf(step)
                            ? 'bg-green-500'
                            : 'bg-gray-200'
                        }`} />
                      )}
                    </div>
                  ))}
                </div>
              </div>

              {/* Body */}
              <div className="flex-1 overflow-y-auto p-6">
                <AnimatePresence mode="wait">
                  {step === 'date_range' && (
                    <motion.div
                      key="date_range"
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: 20 }}
                    >
                      <DateRangeSelector
                        onSelect={handleDateSelect}
                      />
                    </motion.div>
                  )}
                  
                  {step === 'analysis' && (
                    <motion.div
                      key="analysis"
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: 20 }}
                    >
                      <FreshnessAnalyzer
                        warnings={warnings}
                        totalIngredients={totalIngredients}
                        onContinue={() => setStep('strategy')}
                        onBack={handleBack}
                      />
                    </motion.div>
                  )}
                  
                  {step === 'strategy' && (
                    <motion.div
                      key="strategy"
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      exit={{ opacity: 0, x: 20 }}
                    >
                      <StrategySelector
                        warnings={warnings}
                        totalIngredients={totalIngredients}
                        perishableCount={perishableCount}
                        safeCount={safeCount}
                        onSelect={handleStrategySelect}
                        onBack={handleBack}
                      />
                    </motion.div>
                  )}
                  
                  {step === 'generating' && (
                    <motion.div
                      key="generating"
                      initial={{ opacity: 0, scale: 0.9 }}
                      animate={{ opacity: 1, scale: 1 }}
                      className="text-center py-12"
                    >
                      <motion.div
                        animate={{ rotate: 360 }}
                        transition={{ duration: 2, repeat: Infinity, ease: 'linear' }}
                        className="text-6xl mb-4 inline-block"
                      >
                        🛒
                      </motion.div>
                      <h3 className="text-xl font-bold mb-2">Skapar din inköpslista...</h3>
                      <p className="text-text-secondary">
                        Analyserar ingredienser och optimerar hållbarhet
                      </p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </motion.div>
          </div>
        </>
      )}
    </AnimatePresence>
  )
}